"""user_id -> author로 다시 변경

Revision ID: 86979f2b4ea9
Revises: 58828a27dfcb
Create Date: 2025-04-24 17:43:07.130587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86979f2b4ea9'
down_revision = '58828a27dfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('comments_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author'], ['username'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('posts_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author'], ['username'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_ibfk_3', 'users', ['user_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###
