"""post, comment 컬럼명 변경

Revision ID: 8a09a7b83f8b
Revises: 989cb0f01d96
Create Date: 2025-04-24 12:21:00.861966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a09a7b83f8b'
down_revision = '989cb0f01d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writer', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['writer'], ['username'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('writer', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['writer'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('writer')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('writer')

    # ### end Alembic commands ###
